version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16.13.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          key: app-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test

  deploy-to-aws-s3:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Deploy to S3
          command: |
            # Add your deployment script here

  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Deploy to CloudFront
          command: |
            # Add your deployment script here

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deploy-to-aws-cloudfront:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
